const express = require('express');
const router = express.Router();
const { auth } = require('../middlewares/auth');
const { allowRoles } = require('../middlewares/roleCheck');
const { createNotice, getNotices, getAllNotices, deleteNotice } = require('../controllers/notice.controller');
router.get('/', auth, getNotices);
router.get('/all', auth, allowRoles('admin','manager','supervisor'), getAllNotices);
router.post('/', auth, allowRoles('admin','manager','supervisor'), createNotice);
router.delete('/:id', auth, allowRoles('admin','manager','supervisor'), deleteNotice);
module.exports = router;
